### ISSUE TITLE
Changes to ISession in Pyramid  1.9/2.0

### ISSUE THREAD

**Issue by slav0nic** [jvanasco/pyramid_session_redis#19]
CSRF functionality was reworked in pyramid 1.9 and now it not related to session functionality.

PR with changes https://github.com/Pylons/pyramid/pull/3019/files

New `ISession`: https://github.com/Pylons/pyramid/blob/d32e4775e6da03720a9d3b239efeec956101e954/src/pyramid/interfaces.py#L1083-L1087

Also will be fine prepare to Pyramid 2.0 and migrate from Pickle to json based sessions
https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/sessions.html#upcoming-changes-to-isession-in-pyramid-2-0

Current pyramid version still use `LegacySessionCSRFStoragePolicy` (that use `request.session`), but will be fine ready to follow new standard before it will be droped.

**Comment by jvanasco** [comment]
Thanks for creating the issue.  I've tagged this 1.9 and 2.0, but no changes are being scheduled/assigned.  This project is really aiming for longterm stability and not requiring people to upgrade Pyramid to use it when not necessary.  If Pyramid has a breaking change on compatibility, this project has to adapt and issue a release for a new minimum version -- but these topics aren't breaking.

## ISession Change

The change in Pyramid only concerned the core interface requirements. Sessions were previously *required* to handle the csrf functionality, now that is *optional*.  As you noted, Pyramid 1.9+ ships with a `LegacySessionCSRFStoragePolicy` (https://github.com/Pylons/pyramid/blob/587fe72fae0efda3a860d37a1ea2449a41dab622/src/pyramid/csrf.py#L21-L50) which still utilizes the session for storage.  Even when that is deprecated, this library will likely still support it for several years to maintain backwards compatibility for users who roll their own version, and allow people to migrate their legacy systems or handle their application design requirements. 

## Pickle/Json Serialization

Pickle/cPickle is only implemented as the default serializer for this library and in tests; I am wary of changing this to something else as backwards compatibility will be affected for people who are not on Pyramid 2.0.  I do not want to force the legacy users onto a Pyramid 2.0 policy or upgrading to Pyramid 2.0 if they are below it.   If this library were to make any changes to this (before there are any changes in Pyramid that require Pyramid2.x to be the minimum version required for this project), I am currently leaning towards removing the default and raising an exception on startup if a serializer is not specified.

**Comment by slav0nic** [comment]
I think this can be solve in same way as in pyramid: rename current serializer to LegacyRedisSerializer and make it default, create new that follow new ISession changes (maybe with share functionality via mixins), JSON serializer, pickle less SignedCookieSessionFactory (`signed_serialize` deprecated too) etc

**Comment by jvanasco** [comment]
There is no change needed with ISession.  The updated interface simply made the `new_csrf_token` and `get_csrf_token` methods "not required", which made them "optional".  Classes are required to support an Interface's methods, but aren't prohibited from having their own.  Splitting this stuff out and supporting multiple mixins or sessions would create complexity that is currently unnecessary and will need extensive testing. 

In terms of serializers, `signed_serialize` will be removed in Pyramid 2.0 so that is a breaking change and will require a release.

**Comment by jvanasco** [comment]
Changes for this ticket are now in master; they will be part of the 1.5.0 release after some more testing.

To handle this, the following will be happening:

* The value stored in the cookie has been migrated from the deprecated `signed_serialize` to `webob.cookie.SignedSerializer`.  As this value is just the string identifier of the backend session key, JSON serialization is not needed, and a passthrough "_NullSerializer" is used (to invoke `webob.cookie.SignedSerializer` in the same way Pyramid now does).

* The above required some refactoring of the non-public functions `_get_session_id_from_cookie` and `_set_cookie`

* A new namespace `pyramid_session_redis.legacy` is introduced.  This contains:

*    The `signed_serialize` and `signed_deserialize` functions, directly copied from Pyramid, to allow for backwards compatibility
*    A new `GracefulCookieSerializer` that can help users migrate cookies from the old format to a new format 

* Custom cookie "serialization" can be obtained by specifying a `cookie_signer` kwarg to `RedisSessionFactory`.  This isn't really serialization though; the input is a string.  it's just a cookie signer.

**Comment by jvanasco** [comment]
v1.5.1 is live; please note this contains the security fix you identified,so sessions may not be valid anymore. there is a temporary migration workaround though (see the changelog)
