### ISSUE TITLE
Please add support for setting SameSite on cookies

### ISSUE THREAD

**Issue by Deimos** [jvanasco/pyramid_session_redis#22]
Hey jvanasco,

I was just [reading about the new-ish `SameSite` attribute that can be set on cookies](https://scotthelme.co.uk/csrf-is-dead/#samesitecookies), and it seems like it would be great to be able to set on session cookies.

Pyramid already supports it (via webob) with the `samesite` argument to `Response.set_cookie()`, here's the docs for that:

```
``samesite``

  A string representing the ``SameSite`` attribute of the cookie or
  ``None``. If samesite is ``None`` no ``SameSite`` value will be sent
  in the cookie. Should only be ``"Strict"`` or ``"Lax"``.
```

It would be nice to have a config setting for pyramid_session_redis similar to the existing cookie ones to be able to set this.

I can probably do a pull req for it if you'd like, let me know.

**Comment by Deimos** [comment]
One note is that I guess this might cause a minimum Pyramid/webob version requirement. It looks like support for it was added in WebOb 1.8.0: https://docs.pylonsproject.org/projects/webob/en/stable/changes.html#experimental-features

**Comment by jvanasco** [comment]
this sounds like a good idea. 

i was going to ask you to generate a PR, but I think I have an idea on how I want to implement this.   i'll take a first try and perhaps you can help out with come comments/code-review/patches?

**Comment by Deimos** [comment]
Sure, that sounds good to me. Thanks!

**Comment by jvanasco** [comment]
#23 has my initial idea.  it should keep things working on older webob without a required version bump.  i think pyramid 1.9 uses an unsupported webob, and I'm not sure about api changes between 1.9 and 1.10, so  I didn't want to force a potential compatibility issue with pyramid too.

**Comment by jvanasco** [comment]
This is live in master, will be in a 1.5.0 release

**Comment by Deimos** [comment]
Great, thanks very much!

**Comment by jvanasco** [comment]
v1.5.1 is live; please note this contains a security fix and your sessions may not be valid anymore. there is a temporary migration workaround though (see the changelog)
