### ISSUE TITLE
should_persist crashes with TypeError in hashed_value function

### ISSUE THREAD

**Issue by robvdl** [jvanasco/pyramid_session_redis#28]
When doing this which is the only line in the hashed_value function:

    hashlib.md5(serialized).hexdigest()

It raises this (where it refers to the content of serialized):

    TypeError: Unicode-objects must be encoded before hashing

I am using the latest Pyramid and Python 3.6 on Bionic in a virtualenv. I'll dig a little deeper see if it's not something I am doing, I recently upgraded from pyramid-redis-sessions.

I've already cleared my session data from Redis just in case.

**Comment by robvdl** [comment]
Ok so the issue seems to be if detect_changes is True (which happens to be the default).

Looks like there might be a regression in the hashed_value method that does this check.

**Comment by robvdl** [comment]
The issue here is "serialized" is a string not bytes and md5() requires bytes.

Has this code been tested on Python 3?

    hashlib.md5(serialized.encode()).hexdigest() fixes it

But is serialized always a str in Python 3? Do we even care supporting Python 2 (a dead language) at this point in time?

It seems the old library was importing text_ from pyramid.compat still, possibly for python2/3 mixed support but that is gone in this library. Is Python 2 support stripped out fully? If so I'm happy to send a patch for Python 3 only.

**Comment by robvdl** [comment]
sometimes serialized is already bytes and sometimes it's str that is the tricky bit, still trying to figure that one out.

It appears it was meant to be bytes but the hashed_value function doesn't state that in it's docstring or type hints which would be helpful when debugging this, that this is always the case.

**Comment by jvanasco** [comment]
Thanks for pointing this out. I should add a test for `json` serialization and perhaps add some docs on this; i mostly use `msgpack` which outputs bytes - had I used json, I think I'd probably have made this bit more clear or changed the API slightly.

**Comment by robvdl** [comment]
No worries. We use json.dumps and json.loads in this way which works for us:

```python
serialize = lambda s: json.dumps(s).encode('utf-8')
deserialize = lambda s: json.loads(s.decode('utf8'))
````

We always make sure we put simple dicts and lists into our session only so that have no problem serialising things to JSON instead of pickle, we have a rule never to put objects into the session.

Between upgrading to this library, I simply needed to add .encode('utf-8') to the serializer, the deserialize already had decode('utf-8') on it before.
