### ISSUE TITLE
Pyramid 2.0 support?

### ISSUE THREAD

**Issue by Estartu** [jvanasco/pyramid_session_redis#32]
Pyramid 2.0 is now released. 

When will v1.6 be released to be able to use pyramid_session_redis with pyramid 2.0

**Comment by jvanasco** [comment]
There is no ETA for a 1.6 release.

For those that need to deploy under Pyramid 2.0, there is now a "concept_a" branch for 1.6 (https://github.com/jvanasco/pyramid_session_redis/tree/1.6-branch-concept_a), which works with Pyramid 2.0 and is tested via #33. 

While this branch is functional, it is not likely to mature into the `1.6-branch` or a release.  It is being provided to Pyramid 2.0 adopters as a temporary bridge.  The 1.6 branch is now favored to support Python2+3 and Pyramid 1.10+2.0.

**Comment by jvanasco** [comment]
1.6 is now live on github and pypi. it is fully backwards compatible with pyramid1.x
