### ISSUE TITLE
"Placeholder" sessions being created by first hit after browser restart

### ISSUE THREAD

**Issue by Deimos** [jvanasco/pyramid_session_redis#4]
Hi again, @jvanasco. I ran into another instance of "placeholder" sessions being created today, similar to https://github.com/jvanasco/pyramid_session_redis/issues/2 and figured you'd probably want to know about it.

I'm not sure of the cause (though I could help investigate if needed), but each time I restart my browser, my first hit to the site will cause one of those unused placeholder sessions to be created. I still end up using the same session as before the browser restart, but an extra is created and stored in redis.

I confirmed that this happens on v1.2.0 as well, so it's not caused by the fix for the previous issue.

Thanks again (and let me know what you think about just closing [my PR](https://github.com/jvanasco/pyramid_session_redis/pull/3), I really don't mind if you just want to close it).

**Comment by jvanasco** [comment]
Could you share your .ini config for the sessions and browser version?  It would be easier to recreate the issue with that info.

**Comment by Deimos** [comment]
Hmm, after playing with a few possibilites (disabling extensions and such), I think it's being caused somehow by the setting in Firefox (50.1.0 on Ubuntu) for "Accept third-party cookies: Never". If I change that setting to "Always" or "From visited", I don't get a placeholder on restart. But with it set to "Never" it seems to always happen on restart.  I'm not sure if it could be relevant, but the site is also using a self-signed certificate so there's a security exception involved as well.

I'm also not seeing the placeholders being created by doing the same thing in Chromium (regardless of whether third-party cookies are blocked or allowed). So it could just be a pretty niche Firefox-related issue.

The .ini settings are pretty simple, but in case it's useful:

```
redis.sessions.secret = completely_insecure_secret
redis.sessions.unix_socket_path = /run/redis/socket
redis.sessions.prefix = session:
redis.sessions.timeout = 86400
```

**Comment by jvanasco** [comment]
thanks.  i have some ideas on why this may happen, and may end up fixing it as I merge some of your PR in (integrating your stuff led me to realizing there were a few edge cases).

browsers all have their own ways of handling cookies in various situations, often not making much sense.  sometimes a path or timeout value will bust it.

**Comment by jvanasco** [comment]
Unfortunately, I can't re-create this on my Macbook (I set up a self-signed cert on a simple application fronted by nginx, and tried to recreate not-storing and permanently-storing the exception. no luck).  It doesn't happen on any browsers.

A possible situation (wild guess here), is that your Firefox is issuing multiple requests (one before you confirm the security exception, one after).  You could test this with extended logging on the HTTPs server and pyramid.

**Comment by Deimos** [comment]
Not a big deal at all, obviously must just be a really specific combination of browser, settings, and maybe even OS. Thanks for looking into it.
