### ISSUE TITLE
Make a new release without restricting Pyramid version

### ISSUE THREAD

**Issue by nandoflorestan** [jvanasco/pyramid_session_redis#42]
Hello there, thank you for the code and the awesome fixes!

Now why am I here?

Pyramid 2.0 was released in March 2021.  As I upgrade to Pyramid 2.0, pip takes a long time to finish installing my requirements.txt, so long in fact that I stopped it and re-ran it with `--use-deprecated=legacy-resolver`.  In this mode it finishes quickly, but says:

    ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
    pyramid-session-redis 1.5.3 requires pyramid<2,>=1.3, but you'll have pyramid 2.0 which is incompatible.

Since my web app is working anyway, I think it turns out that pyramid_session_redis 1.5.3 is probably fine with pyramid 2.0.  I think you restricted the compatible version to be cautious, but now it's time to make a release without an upper bound on the pyramid version...

Please.

**Comment by jvanasco** [comment]
The current version of this package is 1.6.1, which is compatible with pyramid 1.3+ and pyramid 2.x

Unless your app is pinned to 1.5.3, ‘pip install —upgrade pyramid_session_redis’ is all your need to do.  Maybe there is a version defined in your setup.py or requirements file.

**Comment by nandoflorestan** [comment]
You are absolutely right.  Thank you for helping me out!!!
