### ISSUE TITLE
How to "log off all devices" for a given user?

### ISSUE THREAD

**Issue by hyperknot** [jvanasco/pyramid_session_redis#45]
A common security requirement in session handling is to "log off all devices" for a given user. Basically removing all sessions for a given user.

How would you handle this with this library? As I understand this library, this needs a manual for loop on all keys of the Redis db, which will be kind of slow. There is no way around it, or is there?

Still, with the manual for loop, how would you do it? Can you share a snippet or something which goes through the whole Redis DB and decodes each session and deletes the ones with the matching user_id?

**Comment by jvanasco** [comment]
I definitely would not handle that by iterating the Redis data store.  Even if the payload were in json or msgpack, scripting that serverside with a Redis hosted Lua script would still be incredibly slow.

I think a typical way of handling that is to log, in a RDBMS or similar, session logins:

* user id
* session id
* login metadata (datetime, geoip, etc)

Then you can query by a user id, display to the user their active sessions, extend an option to remove any or all sessions, and do so through the session id.

That is just one way, I can think of a few methods, but they all involve a bit of application design logic to protect against bottlenecks.

Personally, I would probably implement some option that supports client-side sessions as well - which would probably necessitate validating a session was still allowed after loading it.  

I've seen some projects store sessions by user-id to support cross-device sessions, and map the user-based session to the cookie based session id via internal systems.  

As much as I'd love for this library to support any things like that directly, I think this sort of functionality is far beyond the scope of a generalized "sessions" library and really in the realm of customized application design.

**Comment by hyperknot** [comment]
Thanks for the response. Since I'm already loading the user's row from SQL on each request to check for deleted users, etc. I'll add a check there as you've suggested. Basically a new column "sessions_revoked_time", whose timestamp is compared with the current time.

On Redis side this will just let those old sessions expire, I think it's a perfect solution for my use-case.

**Comment by hyperknot** [comment]
One thing not clear is how can I get the session's creation date from the session object? Is this supported?

**Comment by jvanasco** [comment]
> One thing not clear is how can I get the session's creation date from the session object? Is this supported?

The session works by managing a dict with [a specific structure](https://github.com/jvanasco/pyramid_session_redis/blob/main/src/pyramid_session_redis/util.py#L138-L155), which is basically metadata + a "managed dict".

Anything you store in the session goes into the [RedisSession.managed_dict](https://github.com/jvanasco/pyramid_session_redis/blob/bfc23cebb6f301b01e484ab2a618ec41d53b3bfc/src/pyramid_session_redis/session.py#L500-L528
) - which is the actual session data.

The `RedisSession._session_state` attribute can be read directly, and contains the metadata and the managed dict.

However all the metadata is available off helper properties on the RedisSession itself.

In this case, the creation date is exposed via a [`RedisSession.created`](https://github.com/jvanasco/pyramid_session_redis/blob/bfc23cebb6f301b01e484ab2a618ec41d53b3bfc/src/pyramid_session_redis/session.py#L354-L377) property.

**Comment by hyperknot** [comment]
Thanks, I've just found it. Basically with the below snippet I can achieve what I wanted:

```
if user_obj.sessions_revoked_time:
    session_created_time = datetime.datetime.utcfromtimestamp(request.session.created)
    if session_created_time <= user_obj.sessions_revoked_time:
            request.session.invalidate()
            headers = forget(request)
            return HTTPFound(location='/', headers=headers)
```
